;*****************************************************************
;
;	Light Speed Player v1.04
;	Fastest Amiga MOD player ever :)
;	Written By Arnaud Carré (aka Leonard / OXYGENE)
;	https://github.com/arnaud-carre/LSPlayer
;	twitter: @leonard_coder
;
;	"Insane speed" player version ( half scanline average player time! )
;	(this source code is generated by LSPConvert)
;	You can also use the generic LightSpeedPlayer.asm player ( less than 512bytes! )
;
;	MOD in  : 206KiB + 38KiB (rink-a-dink.mod)
;	LSP out : 206KiB + 23KiB
;
;	--------How to use--------- 
;
;	bsr LSP_MusicDriver+0 : Init LSP player code
;		a0: LSP music data(any memory)
;		a1: LSP sound bank(chip memory)
;		a2: DMACON 8bits byte address
;
;	bsr LSP_MusicDriver+4 : LSP player tick (call once per frame)
;		a6: should be $dff0a0 (and not $dff000)
;		Used regs: d0/a0/a1/a2/a3/a4
;
;*****************************************************************

	opt o-	; switch off ALL optimizations(we don't want vasm to change some code size, and all optimizations are done!)

LSP_MusicDriver:
			bra.w	.LSP_PlayerInit

;LSP_MusicDriver+4		; Player tick to call each frame
			lea		.LSPVars+8(pc),a1
			move.l	(a1),a0		; byte stream
.process:	moveq	#0,d0
			move.b	(a0)+,d0
			add.w	d0,d0
			move.w	.LSP_JmpTable(pc,d0.w),d0	; 14 cycles
			jmp		.LSP_JmpTable(pc,d0.w)		; 14 cycles

.r_rewind:	move.l	0-8(a1),16-8(a1)
			move.l	24-8(a1),a0
			bra.s	.process


.LSP_JmpTable:		; (240 codes)
			dc.w	-1		; extended code
			dc.w	.r_None-.LSP_JmpTable
			dc.w	.r_Dv-.LSP_JmpTable
			dc.w	.r_Bv-.LSP_JmpTable
			dc.w	.r_ArCr-.LSP_JmpTable
			dc.w	.r_Cr-.LSP_JmpTable
			dc.w	.r_Dp-.LSP_JmpTable
			dc.w	.r_ArBrCr-.LSP_JmpTable
			dc.w	.r_Ctv-.LSP_JmpTable
			dc.w	.r_Ap-.LSP_JmpTable
			dc.w	.r_Av-.LSP_JmpTable
			dc.w	.r_Ct-.LSP_JmpTable
			dc.w	.r_AtvCtv-.LSP_JmpTable
			dc.w	.r_BrCr-.LSP_JmpTable
			dc.w	.r_AtvCt-.LSP_JmpTable
			dc.w	.r_AtvpCt-.LSP_JmpTable
			dc.w	.r_Cp-.LSP_JmpTable
			dc.w	.r_ArCrDr-.LSP_JmpTable
			dc.w	.r_Bp-.LSP_JmpTable
			dc.w	.r_AvBv-.LSP_JmpTable
			dc.w	.r_ArBrCrDrp-.LSP_JmpTable
			dc.w	.r_BvCvp-.LSP_JmpTable
			dc.w	.r_ArBvCr-.LSP_JmpTable
			dc.w	.r_AtvpCtv-.LSP_JmpTable
			dc.w	.r_Ar-.LSP_JmpTable
			dc.w	.r_ArCrDrp-.LSP_JmpTable
			dc.w	.r_AtvBtvpCt-.LSP_JmpTable
			dc.w	.r_ArBrCrDr-.LSP_JmpTable
			dc.w	.r_CrDp-.LSP_JmpTable
			dc.w	.r_Ctvp-.LSP_JmpTable
			dc.w	.r_AtpBtvpCtv-.LSP_JmpTable
			dc.w	.r_Cv-.LSP_JmpTable
			dc.w	.r_BtvpCtv-.LSP_JmpTable
			dc.w	.r_Atvp-.LSP_JmpTable
			dc.w	.r_ApCr-.LSP_JmpTable
			dc.w	.r_Atv-.LSP_JmpTable
			dc.w	.r_ArCrDp-.LSP_JmpTable
			dc.w	.r_ArBrCrDp-.LSP_JmpTable
			dc.w	.r_ArBr-.LSP_JmpTable
			dc.w	.r_Br-.LSP_JmpTable
			dc.w	.r_BtvpCt-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtv-.LSP_JmpTable
			dc.w	.r_BrCrDrp-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCt-.LSP_JmpTable
			dc.w	.r_ApDv-.LSP_JmpTable
			dc.w	.r_AtCtv-.LSP_JmpTable
			dc.w	.r_ArBrCrDv-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtv-.LSP_JmpTable
			dc.w	.r_AvCr-.LSP_JmpTable
			dc.w	.r_BtCt-.LSP_JmpTable
			dc.w	.r_BrCrDrv-.LSP_JmpTable
			dc.w	.r_Btvp-.LSP_JmpTable
			dc.w	.r_ArCrDv-.LSP_JmpTable
			dc.w	.r_CrDr-.LSP_JmpTable
			dc.w	.r_AtvBvCtv-.LSP_JmpTable
			dc.w	.r_AtpBtvpCtvDtv-.LSP_JmpTable
			dc.w	.r_AtvCtvDtp-.LSP_JmpTable
			dc.w	.r_AtvCtvp-.LSP_JmpTable
			dc.w	.r_AtvpBtvp-.LSP_JmpTable
			dc.w	.r_Dr-.LSP_JmpTable
			dc.w	.r_BvDv-.LSP_JmpTable
			dc.w	.r_AtpCt-.LSP_JmpTable
			dc.w	.r_AtvpBtvCtv-.LSP_JmpTable
			dc.w	.r_CrDrv-.LSP_JmpTable
			dc.w	.r_Dtv-.LSP_JmpTable
			dc.w	.r_BrCrDr-.LSP_JmpTable
			dc.w	.r_AtpCtvDtv-.LSP_JmpTable
			dc.w	.r_CtvDv-.LSP_JmpTable
			dc.w	.r_BtvpCtDtv-.LSP_JmpTable
			dc.w	.r_CrDrp-.LSP_JmpTable
			dc.w	.r_AtpCtvDtvp-.LSP_JmpTable
			dc.w	.r_AtvpCtvDtv-.LSP_JmpTable
			dc.w	.r_ApCrDv-.LSP_JmpTable
			dc.w	.r_AtvpCtvDtp-.LSP_JmpTable
			dc.w	.r_BtvpCtvDtv-.LSP_JmpTable
			dc.w	.r_AtvCtvDt-.LSP_JmpTable
			dc.w	.r_BtvCt-.LSP_JmpTable
			dc.w	.r_Cvp-.LSP_JmpTable
			dc.w	.r_BvCr-.LSP_JmpTable
			dc.w	.r_AtvCtvDtv-.LSP_JmpTable
			dc.w	.r_BrCrDp-.LSP_JmpTable
			dc.w	.r_ArCrDrv-.LSP_JmpTable
			dc.w	.r_CtDtv-.LSP_JmpTable
			dc.w	.r_BvCp-.LSP_JmpTable
			dc.w	.r_AtpBtvpCtvp-.LSP_JmpTable
			dc.w	.r_AtpCtvp-.LSP_JmpTable
			dc.w	.r_AtvBtCt-.LSP_JmpTable
			dc.w	.r_AtvpBtCt-.LSP_JmpTable
			dc.w	.r_AtpBtvpCtvDt-.LSP_JmpTable
			dc.w	.r_BrCrDv-.LSP_JmpTable
			dc.w	.r_AtvpBvCt-.LSP_JmpTable
			dc.w	.r_BvCtv-.LSP_JmpTable
			dc.w	.r_BrDrv-.LSP_JmpTable
			dc.w	.r_AtpBtvpCtDtvp-.LSP_JmpTable
			dc.w	.r_BtpCt-.LSP_JmpTable
			dc.w	.r_BvCt-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtvDtp-.LSP_JmpTable
			dc.w	.r_Btv-.LSP_JmpTable
			dc.w	.r_ApBrCrDv-.LSP_JmpTable
			dc.w	.r_AtBtvpCtvDtp-.LSP_JmpTable
			dc.w	.r_CtvDtp-.LSP_JmpTable
			dc.w	.r_ArBrCrDrv-.LSP_JmpTable
			dc.w	.r_AtvpBtCtv-.LSP_JmpTable
			dc.w	.r_ApBp-.LSP_JmpTable
			dc.w	.r_CtDv-.LSP_JmpTable
			dc.w	.r_CtDt-.LSP_JmpTable
			dc.w	.r_Dtvp-.LSP_JmpTable
			dc.w	.r_BvCtvDv-.LSP_JmpTable
			dc.w	.r_AtvBtvp-.LSP_JmpTable
			dc.w	.r_CtvDtv-.LSP_JmpTable
			dc.w	.r_BpDv-.LSP_JmpTable
			dc.w	.r_AtpBtvpCt-.LSP_JmpTable
			dc.w	.r_BtvpCtvDtvp-.LSP_JmpTable
			dc.w	.r_BtvpCtvDtp-.LSP_JmpTable
			dc.w	.r_AtvpBtvCtvDtp-.LSP_JmpTable
			dc.w	.r_BtvpCtvp-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtvp-.LSP_JmpTable
			dc.w	.r_AtBtvpCtv-.LSP_JmpTable
			dc.w	.r_AtvBtvCt-.LSP_JmpTable
			dc.w	.r_BtpCtvDtv-.LSP_JmpTable
			dc.w	.r_BtvpDtv-.LSP_JmpTable
			dc.w	.r_AtBtvCtv-.LSP_JmpTable
			dc.w	.r_BvCtDv-.LSP_JmpTable
			dc.w	.r_CtDtp-.LSP_JmpTable
			dc.w	.r_AtvBvCtvDtp-.LSP_JmpTable
			dc.w	.r_CtvpDtv-.LSP_JmpTable
			dc.w	.r_ArBrpCrDr-.LSP_JmpTable
			dc.w	.r_BtvCtvDtvp-.LSP_JmpTable
			dc.w	.r_BtvpCtvDt-.LSP_JmpTable
			dc.w	.r_AtpCtvDtp-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtvDt-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtvDtp-.LSP_JmpTable
			dc.w	.r_Dtp-.LSP_JmpTable
			dc.w	.r_AtCt-.LSP_JmpTable
			dc.w	.r_AtBtpCtv-.LSP_JmpTable
			dc.w	.r_AtpCtDtv-.LSP_JmpTable
			dc.w	.r_AtvBtpCtvDt-.LSP_JmpTable
			dc.w	.r_AtvpBtv-.LSP_JmpTable
			dc.w	.r_AtCtvp-.LSP_JmpTable
			dc.w	.r_ArBpCr-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtpDtp-.LSP_JmpTable
			dc.w	.r_CrDv-.LSP_JmpTable
			dc.w	.r_BtvpCtDtvp-.LSP_JmpTable
			dc.w	.r_BtvpDtvp-.LSP_JmpTable
			dc.w	.r_BrDv-.LSP_JmpTable
			dc.w	.r_BtCtvDtp-.LSP_JmpTable
			dc.w	.r_AtpBtvCtvDtp-.LSP_JmpTable
			dc.w	.r_AvBr-.LSP_JmpTable
			dc.w	.r_BvCvpDr-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtvp-.LSP_JmpTable
			dc.w	.r_AvDp-.LSP_JmpTable
			dc.w	.r_Bt-.LSP_JmpTable
			dc.w	.r_ArBv-.LSP_JmpTable
			dc.w	.r_AtBtvp-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtvDt-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtp-.LSP_JmpTable
			dc.w	.r_AvCtvDv-.LSP_JmpTable
			dc.w	.r_AtvDtvp-.LSP_JmpTable
			dc.w	.r_ArBpDr-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtvDtvp-.LSP_JmpTable
			dc.w	.r_Drv-.LSP_JmpTable
			dc.w	.r_AtpBvCtvDtv-.LSP_JmpTable
			dc.w	.r_BrpCrDv-.LSP_JmpTable
			dc.w	.r_ArDv-.LSP_JmpTable
			dc.w	.r_AtBtCt-.LSP_JmpTable
			dc.w	.r_Ctp-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtpDtvp-.LSP_JmpTable
			dc.w	.r_BrpCr-.LSP_JmpTable
			dc.w	.r_AtpBtpCtvDtv-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtp-.LSP_JmpTable
			dc.w	.r_AvBtvpCtv-.LSP_JmpTable
			dc.w	.r_AtvpCtvDtvp-.LSP_JmpTable
			dc.w	.r_BtCtvDt-.LSP_JmpTable
			dc.w	.r_ApBpCpDp-.LSP_JmpTable
			dc.w	.r_AtpBtvCtvDtv-.LSP_JmpTable
			dc.w	.r_BtCtv-.LSP_JmpTable
			dc.w	.r_BtpCtv-.LSP_JmpTable
			dc.w	.r_ArBvCp-.LSP_JmpTable
			dc.w	.r_AtBtCtv-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtvDtv-.LSP_JmpTable
			dc.w	.r_ApBrCr-.LSP_JmpTable
			dc.w	.r_AtBtvpCt-.LSP_JmpTable
			dc.w	.r_ArDp-.LSP_JmpTable
			dc.w	.r_AtvpCtDtv-.LSP_JmpTable
			dc.w	.r_AtvBtpCtv-.LSP_JmpTable
			dc.w	.r_AtvpBtpCt-.LSP_JmpTable
			dc.w	.r_BtpCtvDv-.LSP_JmpTable
			dc.w	.r_AtpBvpCtvDtvp-.LSP_JmpTable
			dc.w	.r_AvBrCr-.LSP_JmpTable
			dc.w	.r_AvCtvDtvp-.LSP_JmpTable
			dc.w	.r_BtvpCv-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtvDt-.LSP_JmpTable
			dc.w	.r_AtvpBvpCtvDtvp-.LSP_JmpTable
			dc.w	.r_ArCpDv-.LSP_JmpTable
			dc.w	.r_AvBp-.LSP_JmpTable
			dc.w	.r_AtvpCtvpDtvp-.LSP_JmpTable
			dc.w	.r_AvBpDr-.LSP_JmpTable
			dc.w	.r_AvCp-.LSP_JmpTable
			dc.w	.r_AvBrCpDr-.LSP_JmpTable
			dc.w	.r_BtvpDt-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtvDtvp-.LSP_JmpTable
			dc.w	.r_BtvCtv-.LSP_JmpTable
			dc.w	.r_AvBvDr-.LSP_JmpTable
			dc.w	.r_ApBrDv-.LSP_JmpTable
			dc.w	.r_Dt-.LSP_JmpTable
			dc.w	.r_ArBrpCrDv-.LSP_JmpTable
			dc.w	.r_BtvpCtvpDtvp-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtvDtv-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtvDtv-.LSP_JmpTable
			dc.w	.r_ArBrpDr-.LSP_JmpTable
			dc.w	.r_AtvBtvpDtp-.LSP_JmpTable
			dc.w	.r_AtvpBvpCvpDtvp-.LSP_JmpTable
			dc.w	.r_AtvpBvCtvDtv-.LSP_JmpTable
			dc.w	.r_BpDr-.LSP_JmpTable
			dc.w	.r_AvBtvpDv-.LSP_JmpTable
			dc.w	.r_CtvDtvp-.LSP_JmpTable
			dc.w	.r_AtvCtvDtvp-.LSP_JmpTable
			dc.w	.r_CtDtvp-.LSP_JmpTable
			dc.w	.r_AtvCtDtp-.LSP_JmpTable
			dc.w	.r_AtBtvpCtvDt-.LSP_JmpTable
			dc.w	.r_BpDp-.LSP_JmpTable
			dc.w	.r_AtvpBtvCt-.LSP_JmpTable
			dc.w	.r_ArBpCrDp-.LSP_JmpTable
			dc.w	.r_AtpCtpDtvp-.LSP_JmpTable
			dc.w	.r_AtvpCtvp-.LSP_JmpTable
			dc.w	.r_AtvBtvCtvDtv-.LSP_JmpTable
			dc.w	.r_BtvCtDtv-.LSP_JmpTable
			dc.w	.r_AtpBtvCtvDtvp-.LSP_JmpTable
			dc.w	.r_AtvBtvCtvDtp-.LSP_JmpTable
			dc.w	.r_AtvBvCtvDt-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtDtvp-.LSP_JmpTable
			dc.w	.r_ArDr-.LSP_JmpTable
			dc.w	.r_AtvpBvCtp-.LSP_JmpTable
			dc.w	.r_CpDr-.LSP_JmpTable
			dc.w	.r_ArCp-.LSP_JmpTable
			dc.w	.r_AtvDtv-.LSP_JmpTable
			dc.w	.r_ArBvCvpDr-.LSP_JmpTable
			dc.w	.r_AtpBtvpCtvDtp-.LSP_JmpTable
			dc.w	.r_ArCvp-.LSP_JmpTable
			dc.w	.r_rewind-.LSP_JmpTable
			dc.w	$ffff		; SetBpm code (not used in this music)

.LSPVars:	dc.l	0			; 0  word stream loop
			dc.w	0			; 4  reloc has been done
			dc.w	0			; 6  current music BPM
			dc.l	0			; 8  byte stream
			dc.l	0			; 12 m_lfmDmaConPatch
			dc.l	0			; 16 word stream
			dc.l	0			; 20 word stream loop
			dc.l	0			; 24 byte stream loop

; WARNING: in word stream, instrument offset is shifted by -12 bytes (3 last long of .LSPVars)
.LSP_InstrumentInfo:			; (28 instruments)
			dc.w	$0000,$95c0,$30c3,$0000,$b928,$1f0f
			dc.w	$0000,$0004,$0a19,$0000,$0dfe,$031c
			dc.w	$0001,$815c,$09ad,$0001,$815c,$0001
			dc.w	$0000,$1436,$0329,$0000,$1436,$0001
			dc.w	$0002,$1c3e,$0851,$0002,$1c3e,$0001
			dc.w	$0000,$1a88,$02a1,$0000,$1a88,$0001
			dc.w	$0000,$1fca,$3afb,$0000,$1fca,$0001
			dc.w	$0001,$e712,$1a96,$0002,$0b84,$085d
			dc.w	$0000,$f746,$07b7,$0000,$f746,$0001
			dc.w	$0001,$1540,$0845,$0001,$1540,$0001
			dc.w	$0001,$06b4,$0746,$0001,$06b4,$0001
			dc.w	$0001,$31c2,$03a3,$0001,$31c2,$0001
			dc.w	$0001,$7078,$0872,$0001,$7078,$0001
			dc.w	$0001,$3908,$0ed3,$0001,$3908,$0001
			dc.w	$0002,$d77e,$1728,$0002,$d77e,$0001
			dc.w	$0002,$7996,$0937,$0002,$7996,$0001
			dc.w	$0001,$94b6,$292e,$0001,$94b6,$0001
			dc.w	$0001,$5eee,$08c5,$0001,$5eee,$0001
			dc.w	$0003,$05ce,$110a,$0003,$05ce,$0001
			dc.w	$0002,$3a9e,$1f7c,$0002,$3a9e,$0001
			dc.w	$0002,$2ce0,$06df,$0002,$2ce0,$0001
			dc.w	$0003,$27e2,$037f,$0003,$27e2,$0001
			dc.w	$0003,$2ee0,$039a,$0003,$2ee0,$0001
			dc.w	$0002,$c218,$0ab3,$0002,$c218,$0001
			dc.w	$0002,$8c04,$1645,$0002,$9ca0,$0df7
			dc.w	$0002,$b88e,$04c5,$0002,$b88e,$0001
			dc.w	$0001,$25ca,$05fc,$0001,$25ca,$0001
			dc.w	$0001,$56ae,$0420,$0001,$56ae,$0001

.resetv:	dc.l	0,0,0,0

; a0: music data (any mem)
; a1: sound bank data (chip mem)
; a2: 8bit DMACON byte address
.LSP_PlayerInit:
			move.l	#$1cf8831d,d0
			cmp.l	(a1),d0
			bne.s	.dataError
			cmpi.l	#'LSP1',(a0)+
			bne.s	.dataError
			cmp.l	(a0)+,d0
			bne.s	.dataError
			lea		846(a0),a0		; skip header
			lea		.LSPVars(pc),a3
			move.l	a2,12(a3)
			move.l	a0,16(a3)		; word stream ptr
			movea.l	a0,a4
			add.l	#9634,a4
			move.l	a4,8(a3)		; byte stream ptr

			move.l	a0,(a3)	; word stream loop ptr
			move.l	a4,24(a3)	; byte stream loop ptr
			tst.b	4(a3)
			bne.s	.noReloc
			st		4(a3)
			moveq	#28-1,d0
			lea		.LSP_InstrumentInfo(pc),a0
			move.l	a1,d1
.rloop:		add.l	d1,(a0)
			add.l	d1,6(a0)
			lea		12(a0),a0
			dbf		d0,.rloop
.noReloc:	bset.b	#1,$bfe001	; disable this fucking Low pass filter!!
			lea		.LSPVars+6(pc),a0
			move.w	#125,(a0)		; music BPM
			rts

.dataError:	illegal
; 239 specific callback
.r_None:
		move.l	a0,(a1)+
		rts

.r_Dv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		rts

.r_Bv:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		rts

.r_ArCr:
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_Cr:
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		rts

.r_Dp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.l	a0,(a1)
		rts

.r_ArBrCr:
		move.l	a0,(a1)+
		lea		.resetv+4(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_Ctv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Ap:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_Av:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		rts

.r_Ct:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BrCr:
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_AtvCt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpCt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_Cp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	a0,(a1)
		rts

.r_ArCrDr:
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	4(a4),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_Bp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	a0,(a1)
		rts

.r_AvBv:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		rts

.r_ArBrCrDrp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_BvCvp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	a0,(a1)
		rts

.r_ArBvCr:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvpCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_Ar:
		move.l	a0,(a1)+
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_ArCrDrp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	4(a4),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtvBtvpCt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBrCrDr:
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_CrDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_Ctvp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtpBtvpCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Cv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		rts

.r_BtvpCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Atvp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ApCr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_Atv:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArCrDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_ArBrCrDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv+4(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_ArBr:
		move.l	a0,(a1)+
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_Br:
		move.l	a0,(a1)+
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_BtvpCt:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BrCrDrp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ApDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_AtCtv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBrCrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		lea		.resetv+4(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvBtvpCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AvCr:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		rts

.r_BtCt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BrCrDrv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_Btvp:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArCrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_CrDr:
		move.l	a0,(a1)+
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		rts

.r_AtvBvCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtpBtvpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvCtvp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtvp:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$03,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Dr:
		move.l	a0,(a1)+
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		rts

.r_BvDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		rts

.r_AtpCt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtvCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_CrDrv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		rts

.r_Dtv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$08,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BrCrDr:
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_AtpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_CtvDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvpCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_CrDrp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_AtpCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ApCrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_AtvpCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BtvpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCtvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BtvCt:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Cvp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	a0,(a1)
		rts

.r_BvCr:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		rts

.r_AtvCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BrCrDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_ArCrDrv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	4(a4),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_CtDtv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BvCp:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	a0,(a1)
		rts

.r_AtpBtvpCtvp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtpCtvp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtCt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtCt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtpBtvpCtvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BrCrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_AtvpBvCt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BvCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BrDrv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_AtpBtvpCtDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtpCt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BvCt:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Btv:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ApBrCrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_AtBtvpCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_CtvDtp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBrCrDrv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvpBtCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ApBp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_CtDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_CtDt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Dtvp:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$08,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BvCtvDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvp:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$03,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_CtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BpDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	a0,(a1)
		rts

.r_AtpBtvpCt:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvpCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvpCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvpCtvp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtvp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtBtvpCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvCt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0a,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtBtvCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BvCtDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_CtDtp:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBvCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_CtvpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBrpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_BtvCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvpCtvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtpCtvDtp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Dtp:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$08,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtCt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtBtpCtv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtpCtDtv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtpCtvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtv:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$03,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtCtvp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBpCr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtpDtp:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_CrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		rts

.r_BtvpCtDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0a,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_BtCtvDtp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtpBtvCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AvBr:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_BvCvpDr:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtvp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AvDp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.l	a0,(a1)
		rts

.r_Bt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBv:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtBtvp:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$03,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AvCtvDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_ArBpDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Drv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		rts

.r_AtpBvCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BrpCrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_ArDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtBtCt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Ctp:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BrpCr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_AtpBtpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtp:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AvBtvpCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BtCtvDt:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ApBpCpDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_AtpBtvCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtCtv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtpCtv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBvCp:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtBtCtv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ApBrCr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_AtBtvpCt:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtvpCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtpCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtpCt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtpCtvDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtpBvpCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AvBrCr:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_AvCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvpCv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBvpCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArCpDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AvBp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	a0,(a1)
		rts

.r_AtvpCtvpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AvBpDr:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	a0,(a1)
		rts

.r_AvCp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	a0,(a1)
		rts

.r_AvBrCpDr:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_BtvpDt:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0a,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvCtv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AvBvDr:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		rts

.r_ApBrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_Dt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$08,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBrpCrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_BtvpCtvpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBrpDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	4(a4),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	8(a4),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtvBtvpDtp:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBvpCvpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBvCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BpDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	a0,(a1)
		rts

.r_AvBtvpDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_CtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_CtDtvp:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCtDtp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtBtvpCtvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BpDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.l	a0,(a1)
		rts

.r_AtvpBtvCt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBpCrDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtpCtpDtvp:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpCtvp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtvCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtpBtvCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBvCtvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArDr:
		move.l	a0,(a1)+
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvpBvCtp:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_CpDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	a0,(a1)
		rts

.r_ArCp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_ArBvCvpDr:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtpBtvpCtvDtp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArCvp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

